[tool.poetry]
name = "notebooks"
version = "0.1.0"
description = ""
authors = ["Lewe Ohlsen <mail@lewe.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
